version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: market_risk_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: risk_user
      POSTGRES_PASSWORD: risk_pw
      POSTGRES_DB: market_risk
    ports:
      - "5432:5432"
    volumes:
      - market_risk_pg_data:/var/lib/postgresql/data

volumes:
  market_risk_pg_data:
